import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[font.normal]
family = "Hack Nerd Font"

[env]
term = "xterm-256color"

# [cursor]
# # Set to false to disable completely
# smooth_motion = true
# # # 0.0 = cursor is not moving, 1.0 = cursor moves instantly
# smooth_motion_factor = 0.2
# # 0.0 = broken, 1.0 = cursor shape is unaffected by movement
# smooth_motion_spring = 0.5
